### ISSUE TITLE
Doesn't load on game version 1.16.1

### ISSUE THREAD

**Issue by JonnyVR1** [headassbtw/ReProcessor#1]
Game version: 1.16.1
Mod version: 1.1.0

Log:
`[ERROR @ 11:36:18 | IPA/Loader] Could not init plugin ReProcessor
[ERROR @ 11:36:18 | IPA/Loader] System.IO.IOException: Sharing violation on path E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\UserData\ReProcessor\Presets\preset.json
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.StreamWriter.CreateFile (System.String path, System.Boolean append, System.Boolean checkHost) [0x0001c] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) [0x00055] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at System.IO.StreamWriter..ctor (System.String path) [0x00008] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at (wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string)
[ERROR @ 11:36:18 | IPA/Loader]   at ReProcessor.JsonIO.SaveJson (ReProcessor.Files.Preset preset, System.String path) [0x00001] in <37908059264f41dd8850c4ad22150aa2>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at ReProcessor.PresetExtensions.Save (ReProcessor.Files.Preset preset) [0x00038] in <37908059264f41dd8850c4ad22150aa2>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at ReProcessor.Plugin..ctor (IPA.Config.Config conf, SiraUtil.Zenject.Zenjector zenjector, IPA.Logging.Logger logger, IPA.Loader.PluginMetadata metadata) [0x00062] in <37908059264f41dd8850c4ad22150aa2>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at (wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,IPA.Loader.PluginMetadata)
[ERROR @ 11:36:18 | IPA/Loader]   at IPA.Loader.PluginExecutor.Create () [0x00016] in <8e98fd56b0d143f6ba8e9ca7b94817e7>:0 
[ERROR @ 11:36:18 | IPA/Loader]   at IPA.Loader.PluginLoader.InitPlugin (IPA.Loader.PluginMetadata meta, System.Collections.Generic.IEnumerable`1[T] alreadyLoaded) [0x001b0] in <8e98fd56b0d143f6ba8e9ca7b94817e7>:0 `

**Comment by JonnyVR1** [comment]
Nevemind, deleted the ReProcessor.json file but not the presets one in UserData\ReProcessor

**Comment by headassbtw** [comment]
yea, this is an artifact of me rewriting the presets system
