### ISSUE TITLE
Bloom settings show "Invalid BSML"

### ISSUE THREAD

**Issue by vigdzufi** [headassbtw/ReProcessor#3]
Game version: 1.16.2
Mod version: 1.2.0

Mod not showing up in lobby menu. Can still access mod through camera button when selecting a song. Bloom settings are not responsive and there are no sliders (see attached screen capture). Logs attached as well.
![Beat Saber Screenshot 2021 07 05 - 14 37 45 55](https://user-images.githubusercontent.com/32203815/124468587-f41dd100-dda1-11eb-88be-88cbc6502733.png)
[_latest.log](https://github.com/headassbtw/ReProcessor/files/6764022/_latest.log)

**Comment by headassbtw** [comment]
for some reason, it can't find the camera (or zenject isn't giving it to me) and i honestly dunno how to fix this, 

unless you're on 1.15, but you aren't...

**Comment by headassbtw** [comment]
weird issue that i can't reproduce on my end...

**Comment by headassbtw** [comment]
i do recall another person saying BS+ was causing them problems with ReProcessor, however in a new update i will build in something that doesn't load in the menu if the camera can't be found

**Comment by headassbtw** [comment]
closed for inactivity
