### ISSUE TITLE
plz update to 1.18.0 (or whatever the latest update at the time)

### ISSUE THREAD

**Issue by ggggggggggggggggggggglo** [headassbtw/ReProcessor#5]
yes

**Comment by headassbtw** [comment]
gonna work on it, bit busy with other things

trust me, i want to updated it as well, the game looks like absolute garbage without

**Comment by ggggggggggggggggggggglo** [comment]
i also love the bloom effects and stuff that this mod can do

**Comment by headassbtw** [comment]
check BSMG, i updated it
