### ISSUE TITLE
1.19 update coming?

### ISSUE THREAD

**Issue by ghost** [headassbtw/ReProcessor#6]
My eyes hurt, I need this. Any plans on updating it?

**Comment by headassbtw** [comment]
i'm working on a total rewrite of the mod from the ground up to fix my spaghetti code, but i might just update this one in the meantime

**Comment by headassbtw** [comment]
the rewrite may be on hold for a while due to me being so far behind on schoolwork it hurts, and finals week

**Comment by ghost** [comment]
yeah update would be appreciated but school do be more important so gl with that

**Comment by headassbtw** [comment]
finished the rewrite, works on 1.19
